### ISSUE TITLE
white background in contributors during loading animation

### ISSUE THREAD

**Issue by Divyesh-Thirukonda** [Divyesh-Thirukonda/gopherguessr#30]
A loading screen so users know that the button actually got clicked (Divyesh is working on it)

**Comment by Divyesh-Thirukonda** [comment]
Nearly done... slight issue with the contributors section. That section, when isLoading / the anim is active, has a white background instead of drone background

**Comment by jinexists** [comment]
Looks fixed to me?

**Comment by Divyesh-Thirukonda** [comment]
![image](https://github.com/user-attachments/assets/ab1ecef7-2864-4ce6-8e63-305ed6f0c8f3)

**Comment by jinexists** [comment]
Very strange, I just tried on Chrome and it happens like your picture shows, but in Safari it doesn't happen...
