### ISSUE TITLE
Game Mode (by difficulty, campus, etc)

### ISSUE THREAD

**Issue by zlarsen23** [Divyesh-Thirukonda/gopherguessr#34]

**Comment by Divyesh-Thirukonda** [comment]
Split game modes by mpls-stpaul campuses (fixes zoom error)

**Comment by Divyesh-Thirukonda** [comment]
Add tiles to home page for each game mode (carousel style?)

**Comment by zlarsen23** [comment]
Yes that is definitely the next step.

**Comment by krthkmgndm** [comment]
Instead of having locations and difficulties be separate, we just have a dropdown pop up when clicking a location setting for difficulty.
