### ISSUE TITLE
Polyline Highlighting

### ISSUE THREAD

**Issue by Divyesh-Thirukonda** [Divyesh-Thirukonda/gopherguessr#49]
When hovering over a polyline, display the image and guessDist that the guess was for (both results and end dialog).

**Comment by Divyesh-Thirukonda** [comment]
![image](https://github.com/user-attachments/assets/eaaff131-0e5f-402a-b0c1-504436b5cc5b)
Could look like this

**Comment by krthkmgndm** [comment]
Gave up

**Comment by rohanm-1** [comment]
I got this to work, I'm talking with Divyesh rn it'll be implemented before presentations
