### ISSUE TITLE
Merging Conflicts

### ISSUE THREAD

**Issue by Divyesh-Thirukonda** [Divyesh-Thirukonda/gopherguessr#54]
We seem to have lost some features and introduced new bugs during this week's merge:
1) When the user gets to the last guess, show the results screen first and then hitting continue on only that last guess should open the end dialog where it shows all the guesses of that game.
2) The buttons on the end dialog are kind of broken. Play Again throws an error about setShowEndDialog but works, and Home button also plays again.

**Comment by krthkmgndm** [comment]
For 2. Deleting setShowEndDialog from EndDialog.js makes the Home button work properly. Not sure why.

**Comment by krthkmgndm** [comment]
Closing issue because we already have unique issues addressing all these points.
