### ISSUE TITLE
bug-results-dialog-on-different-campus

### ISSUE THREAD

**Issue by krthkmgndm** [Divyesh-Thirukonda/gopherguessr#55]
VIewing of the results dialog when a guess is made on the wrong campus (St. Paul vs Minneapolis) breaks, and only displays the line and not the endpoints.

**Comment by Divyesh-Thirukonda** [comment]
Yea that's why I suggested we do a different game mode for each campus. We should remove the option to go to st. paul from the Minneapolis campus.
