### ISSUE TITLE
feature-endDialog-zoom

### ISSUE THREAD

**Issue by krthkmgndm** [Divyesh-Thirukonda/gopherguessr#62]
No zoom logic for the EndDialog right now. Needs to be ported over from ResultsDialog.

**Comment by krthkmgndm** [comment]
Pushed an initial change to dev (f87bb60) to implement zooming.

**Comment by Divyesh-Thirukonda** [comment]
Fixed and pushed solution to dev. Instead of calculating avg dist, I used just the max dist.
